# Generated by Django 2.0 on 2018-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180227_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='altitude',
            field=models.FloatField(default=0, verbose_name='海拔'),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='距离'),
        ),
    ]
