# Generated by Django 2.0 on 2018-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_weixinusers_is_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
