# Generated by Django 2.0 on 2018-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasummary',
            name='created_time',
            field=models.DateField(),
        ),
    ]
