# Generated by Django 2.0 on 2018-02-09 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0002_auto_20180207_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasummary',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DataSummary',
        ),
    ]
