# Generated by Django 2.0 on 2018-02-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0004_auto_20180210_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar_url',
            field=models.CharField(default='', max_length=300, verbose_name='微信头像'),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='', max_length=20, verbose_name='微信昵称'),
        ),
    ]
