# Generated by Django 2.0 on 2018-02-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0006_datadefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadefine',
            name='status',
            field=models.CharField(choices=[('CIM', '已提交'), ('DEL', '已删除'), ('ONL', '已上架')], default='ONL', max_length=5, verbose_name='状态'),
        ),
    ]
