# Generated by Django 2.0 on 2018-03-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0008_auto_20180301_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='target',
            field=models.IntegerField(default=6000, verbose_name='每日步数目标'),
        ),
    ]
