# Generated by Django 2.0 on 2018-03-15 07:05

import adminset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0009_users_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadefine',
            name='pic',
            field=models.ImageField(default='', upload_to=adminset.models.summary_pic_path),
        ),
        migrations.AddField(
            model_name='datadefine',
            name='pic_name',
            field=models.CharField(max_length=30, null=True, verbose_name='文案图片'),
        ),
    ]
