# Generated by Django 2.0 on 2018-03-15 07:50

import adminset.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminset', '0010_auto_20180315_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', upload_to=adminset.models.summary_pic_path)),
                ('status', models.CharField(choices=[('CIM', '已提交'), ('DEL', '已删除'), ('ONL', '已上架')], default='CIM', max_length=5, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='datadefine',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='datadefine',
            name='pic_name',
        ),
        migrations.AlterField(
            model_name='datadefine',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='summarypic',
            name='data_define',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminset.DataDefine'),
        ),
    ]
