# Generated by Django 2.0 on 2018-04-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20180209_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('summary', models.CharField(max_length=50, verbose_name='介绍')),
                ('reward', models.IntegerField(default=0, verbose_name='奖金')),
                ('target_step', models.IntegerField(default=0, verbose_name='目标步数')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('0', '未开始'), ('1', '进行中'), ('2', '已结束'), ('3', '已删除'), ('4', '未参加'), ('5', '已参加')], default='0', max_length=1, verbose_name='活动状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='activitycreate',
            name='user',
        ),
        migrations.AddField(
            model_name='activityjoin',
            name='fabulous',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AddField(
            model_name='activityjoin',
            name='is_observe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityjoin',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='activityjoin',
            name='altitude',
            field=models.FloatField(default=0, verbose_name='海拔'),
        ),
        migrations.AlterField(
            model_name='activityjoin',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='卡路里'),
        ),
        migrations.AlterField(
            model_name='activityjoin',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='距离'),
        ),
        migrations.DeleteModel(
            name='ActivityCreate',
        ),
    ]
