# Generated by Django 2.0 on 2018-04-19 07:30

import activity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20180419_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', upload_to=activity.models.title_pic_path)),
                ('status', models.CharField(choices=[('CIM', '已提交'), ('ONL', '已上线'), ('FIN', '已结束'), ('DEL', '已删除'), ('OBS', '已观战'), ('JOI', '已参加')], default='CIM', max_length=5, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
