# Generated by Django 2.0 on 2018-05-02 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_titlepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('D', '已提交'), ('W', '已上线'), ('C', '已结束')], default='D', max_length=5, verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='activityjoin',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='activityjoin',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
