# Generated by Django 2.0 on 2018-05-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20180502_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityjoin',
            options={},
        ),
        migrations.RemoveField(
            model_name='activityjoin',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='activityjoin',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='activityjoin',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='activityjoin',
            name='step',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('D', '日活动'), ('W', '周活动'), ('C', '自定义')], default='D', max_length=5, verbose_name='活动类型'),
        ),
    ]
