# Generated by Django 2.0 on 2018-05-11 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0008_auto_20180504_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabulous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='activityjoin',
            name='fabulous',
        ),
        migrations.AddField(
            model_name='fabulous',
            name='activity_join',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.ActivityJoin'),
        ),
        migrations.AddField(
            model_name='fabulous',
            name='user_give',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_give', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabulous',
            name='user_receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_receive', to=settings.AUTH_USER_MODEL),
        ),
    ]
